name: flutter_pull_up_down_refresh
description: flutter_pull_up_down_refresh lib allow to pull-up or pull-down in ScrollView, just listen callback both events.
version: 1.0.0
homepage: https://github.com/kdrtech/flutter_pull_up_down_refresh
#repository: https://github.com/kdrtech/flutter_pull_up_down_refresh

environment:
  sdk: '>=3.2.6 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
 flutter:
    sdk: flutter
    
dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

flutter: